/* build_cmudict_subset.js — regenerate cmudict-subset.js (optional, reproducible)
 *
 * Produces window.CMUDICT_SUBSET: { word: "ARPAbet with stress digits", ... }
 * restricted to a common-word list so the demo lexicon stays relevant.
 *
 * Inputs (place alongside this script):
 *   cmudict.dict   — CMU Pronouncing Dictionary
 *                    https://raw.githubusercontent.com/cmusphinx/cmudict/master/cmudict.dict
 *   freq.txt       — one common word per line (e.g. google-10000-english-usa-no-swears.txt)
 * Output:
 *   cmudict-subset.js
 *
 * Stress digits are RETAINED — the Sound & Spelling engine needs them for
 * syllabification (Maximum Onset Principle + stressed-lax-vowel-keeps-coda).
 */
'use strict';
const fs = require('fs');
const cmu = {};
for (const line of fs.readFileSync('cmudict.dict', 'utf8').split('\n')) {
  const noc = line.split('#')[0].trim();
  if (!noc) continue;
  const sp = noc.split(/\s+/);
  const m = sp[0].match(/^(.+?)\(\d+\)$/);          // drop variant markers word(2)
  const base = (m ? m[1] : sp[0]).toLowerCase();
  if (!/^[a-z]+$/.test(base)) continue;
  if (!(base in cmu)) cmu[base] = sp.slice(1).join(' ');   // primary pron only
}
const wanted = new Set(fs.readFileSync('freq.txt', 'utf8').split('\n').map(s => s.trim()).filter(Boolean));
['night', 'school'].forEach(w => wanted.add(w));    // ensure a couple of regression anchors
const out = {};
for (const w of wanted) if (cmu[w] && w.length >= 2) out[w] = cmu[w];
const keys = Object.keys(out).sort();
let js = '/* cmudict-subset.js — General American pronunciations (CMU Pronouncing Dictionary,\n';
js += '   restricted to a common-word list). Values are ARPAbet with stress digits.\n';
js += '   Generated by build_cmudict_subset.js. */\n';
js += '(function(g){ g.CMUDICT_SUBSET = {\n';
js += keys.map(k => '  ' + JSON.stringify(k) + ': ' + JSON.stringify(out[k])).join(',\n');
js += '\n}; })(typeof window!=="undefined"?window:globalThis);\n';
js += 'if (typeof module!=="undefined" && module.exports) module.exports = (typeof window!=="undefined"?window:globalThis).CMUDICT_SUBSET;\n';
fs.writeFileSync('cmudict-subset.js', js);
console.log('wrote cmudict-subset.js with', keys.length, 'words');
